### ISSUE TITLE
Task List Integration

### ISSUE THREAD

**Issue by silveranstavern** [1804-Apr-USFdotnet/Project2-TLM_Notifiy#1]
Integrate task list into the project

- [x] Create TaskItem model in .Models
- [x] Create TaskItem data transfer object model in .BLL
- [x] Create TaskItemRepository  and ITaskItemRepository in Repository.
- [x] Create TaskItemDto controller SL
	- [x] Scaffold controller off of DTO
	- [x] Integrate authentication logic
	- [x] Implement .BLL logic
- [x] Create testable TaskItem business logic in .BLL
	- [x] Get TaskItems associated with user using IUoW
	- [x] Get TaskItem associated with user using IUoW
	- [x] Add TaskItem and associate with user using IUoW
	- [x] Delete TaskItem associated with user using IUoW
	- [x] Update TaskItem associated with user using IUoW

**Comment by silveranstavern** [comment]
Created local feature branch to work on this issue.
